export Attachments from '@design/components/DesignTheme/View/Commons/Attachments';
export Gallery from '@design/components/DesignTheme/View/Commons/Gallery';
export RelatedContents from '@design/components/DesignTheme/View/Commons/RelatedContents';
export CuredBy from '@design/components/DesignTheme/View/Commons/CuredBy';
export Locations from '@design/components/DesignTheme/View/Commons/Locations';
export WideImage from '@design/components/DesignTheme/View/Commons/WideImage';
export SideMenu from '@design/components/DesignTheme/View/Commons/SideMenu';
export PageHeader from '@design/components/DesignTheme/View/Commons/PageHeader';
export RichTextArticle from '@design/components/DesignTheme/View/Commons/RichTextArticle';
export OfficeCard from '@design/components/DesignTheme/View/Commons/OfficeCard';
export Metadata from '@design/components/DesignTheme/View/Commons/Metadata';
export Sharing from '@design/components/DesignTheme/View/Commons/Sharing';
// export Actions from '@design/components/DesignTheme/View/Commons/Actions';
