export BITIcon from './BITIcon';
/** List of icons*/
export ITUser from 'bootstrap-italia/src/svg/it-user.svg';
export ITExpand from 'bootstrap-italia/src/svg/it-expand.svg';
export ITPa from 'bootstrap-italia/src/svg/it-pa.svg';
export ITFacebook from 'bootstrap-italia/src/svg/it-facebook.svg';
export ITTwitter from 'bootstrap-italia/src/svg/it-twitter.svg';
export ITSearch from 'bootstrap-italia/src/svg/it-search.svg';
export ITBurger from 'bootstrap-italia/src/svg/it-burger.svg';
